#!/bin/bash -e
if [ $(getent group admin) ]; then
  echo "Starting FTP Server"
else
  echo Setting credentials to $USERNAME:$PASSWORD
  PASSWORD=$(perl -e 'print crypt($ARGV[0], "password")' $PASSWORD)

  sed s/CREATE_MAIL_SPOOL=yes/CREATE_MAIL_SPOOL=no/ -i /etc/default/useradd
  groupadd -g 1000 $USERNAME
  useradd -g 1000 -m --password $PASSWORD $USERNAME
  chown -R $USERNAME:$USERNAME /ftp
fi
exec /usr/local/sbin/proftpd -n -c /etc/proftpd.conf
